# Generated by Django 5.0.4 on 2024-04-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
    ]
