# Generated by Django 5.0.3 on 2024-04-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_product_issold"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="InCart",
            field=models.BooleanField(default=False),
        ),
    ]
